### ISSUE TITLE
Ruby 3.2 support

### ISSUE THREAD

**Issue by yabenatti** [ckruse/CFPropertyList#62]
CFPropertyList doesn't work with Ruby 3.2. 

Error:

```
 NoMethodError: undefined method `exists?' for File:Class
/.gem/ruby/3.2.0/gems/CFPropertyList-3.0.5/lib/cfpropertylist/rbCFPropertyList.rb:378:in `save'
```

The method `File.exists?` has been deprecated since [Ruby 2.1.0](https://bugs.ruby-lang.org/issues/17391) and was removed on [Ruby 3.2.0](https://www.ruby-lang.org/en/news/2022/04/03/ruby-3-2-0-preview1-released/).

**Comment by ckruse** [comment]
Thanks for reporting! Will release a new version :-)

**Comment by yabenatti** [comment]
Thank you!
